(async => {

    console.log(`miner run test`);

})().catch(err => {

    console.log(`minr run test error:`, err);
    
});